### ISSUE TITLE
IE 11 not working

### ISSUE THREAD

**Issue by werthdavid** [zxing-js/library#7] opened 2018-02-26 10:24 UTC
I know, the Browser is a pain in the ass but it should work with IE 11 as well

**Comment by odahcam** [comment] 2018-02-26 12:41
Oh no! 😢 

Let's give this dinossaur 🐱‍🐉 some attention.

**Comment by odahcam** [comment] 2018-05-16 17:14
As found by @andrevargas:
```bash
yarn build:before && tsc && tsc --target es2017 --outDir esm5 && webpack && webpack --env.prod
```

TS compiler is targeted to output es6 files and is outpiting these in the ES5 folder. 🤦‍♂️

**Comment by devgrigor** [comment] 2018-05-18 14:06
Hi guys I'm the author of https://github.com/zxing-js/ngx-scanner/issues/93 Just FYI the build is not only thing that is crashing IE,I've build es5 correctly on my local and tested. I  noticed few issues with using Array.from function which is crashing IE as well, after some modifications it worked but only on edge, for some reason IE kept loading script, not sure why. Also I failed on building the plugin under prod. I have deadline coming and I will be eternally in your debt if you can give me working release in upcoming few days  :smirk:

**Comment by odahcam** [comment] 2018-05-18 14:10
Next monday we have a release scheduled, probably will be made on next sunday (20). I will do what I can to deploy this little guy working. ;)

**Comment by odahcam** [comment] 2018-05-18 14:13
@devgrigor did you checked your polyfills? IE is known by requiring them to work properly. Wating for this feedback.

**Comment by odahcam** [comment] 2018-05-18 15:49
Sh*t! I believe that as a first step we **must** publish the right EcmaScript files, then let's investigate the IE dinossaur. 🐱‍🐉

**Comment by odahcam** [comment] 2018-05-21 00:10
Build target fixed in 04fac3b. 🙂

**Comment by devgrigor** [comment] 2018-05-21 07:48
Thanks @odahcam I noticed the correct files and I really don't wan't to be a need-picky a*$hole here, but ngx-scanner is still using version 0.3.2 and is always installing that instead of new one, even after 
`npm cache clean --force`

**Comment by devgrigor** [comment] 2018-05-21 08:51
Also figured out why IE is crashing but edge is not. In `@zxing/library` you used `Uint8ClampedArray.from` and `Int32Array.from`  functions and as developer I love the implementation, but those are not covered by default polyfills of angular, the correct polyfill is
```import 'core-js/es6/typed';```
which is solution for IE11, hope this will help in future :slightly_smiling_face:

**Comment by odahcam** [comment] 2018-05-21 12:11
So that's not a bug with the package itself?
Do you think we should add it to the docs as "How to support IE/Edge"?

**Comment by devgrigor** [comment] 2018-05-21 12:15
No the bug is just missing special pollyfill and yes I believe mentioning that will help others. 
Only thing that I'm waiting to close IE issue is the `ngx-scanner`'s new version with updated dependency of `library` package

**Comment by odahcam** [comment] 2018-05-21 12:53
I believe that because of our dependency in `^0.3.2`, npm will just downloads the latest minor version, which is `^0.5.0`. A `npm install` without package-lock is worth a try.

**Comment by devgrigor** [comment] 2018-05-21 13:17
yep, which is done several times now. `npm update` too. Same result

**Comment by odahcam** [comment] 2018-05-21 14:38
Oh, I can try to publish a dev version there so we can test it. Also, I would like to ask to keep this issue open until we add that note about IE in the wiki, thanks. 😄

**Comment by devgrigor** [comment] 2018-05-21 14:42
ok. sure :slightly_smiling_face: Looking forward to it

**Comment by devgrigor** [comment] 2018-05-22 16:13
I know it will work on IE, already tested :slightly_smiling_face: but I need it to work on server. Can I commit the change and make it dev release. If yes please let me know how exactly to do that

**Comment by odahcam** [comment] 2018-06-04 23:47
I will release v0.5.1 with this issue open, please test it to see if it works with the new version. Thx!

**Comment by odahcam** [comment] 2018-06-05 18:46
Closing as this seems to be resolved by polyfills presented in readme and build fixes.

**Closed by odahcam** 2018-06-05 18:46 UTC
Labels: P0, bug, docs, has polyfill, plat: browser, wontfix
