### ISSUE TITLE
IPhone rear camera not working

### ISSUE THREAD

**Issue by DulcineaS** [zxing-js/library#152] opened 2019-04-20 19:05 UTC
Hi, on IPhone I have tow cameras: front and rear. The are listed as sources.  If I choose "camera 0" I get the stream from the front camera. But f I choose "camera 1"  - and this is my rear camera - I get the stream from the front camera, too. How I can change them? Reagrds, Duclinea

**Comment by Matth--** [comment] 2019-04-23 04:35
duplicate of #149

**Comment by odahcam** [comment] 2019-05-23 22:51
One way to workaround is to get available devices from the component's event and then search for the rear camera, something like that: 

```TS
  ngOnInit(): void {
    this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {

      this.availableDevices = devices;

      // selects the devices's back camera by default
      for (const device of devices) {
          if (/back|rear|environment/gi.test(device.label)) {
              this.scanner.changeDevice(device);
              this.currentDevice = device;
              break;
          }
      }
    });
  }
```

**Closed** 2019-05-23 22:51 UTC
